version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - assessment:/data/db
    networks:
      - mongo_network
  mongo_seed:
    image: mongo
    links:
      - mongodb
    volumes:
      - ./data:/data
    command:
      /data/import.sh


volumes:
  assessment:

networks:
  mongo_network: