name: Build Backend and Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_API_HOST=http://127.0.0.1:8080
    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Setup Java
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'
    
    # Build Backend with Gradle
    - name: Build Backend
      working-directory: backend-spring-mongo-app
      run: |
        ./gradlew build

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
        
    # Install dependencies and build frontend
    - name: Build Frontend
      working-directory: frontend-react-app
      run: |
        npm install
        npm test
        npm run build

    # Store artifacts
    - name: Store Backend JAR
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: backend
        path: backend/build/libs/*.jar

    - name: Store Frontend Build
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: frontend
        path: frontend/dist/